//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#ifndef _NF_DISPLAYSLIB_H_
#define _NF_DISPLAYSLIB_H_

#include <nanoCLR_Interop.h>
#include <nanoCLR_Runtime.h>
#include <nanoPackStruct.h>

struct Library_NF_DisplaysLib_nf_lib_Display_LiquidCrystal_I2C
{
    NANOCLR_NATIVE_DECLARE(NativeTest___STATIC__BOOLEAN__BOOLEAN);

    //--//

};

extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_NF_DisplaysLib;

#endif  //_NF_DISPLAYSLIB_H_
