//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "nf_lib.h"

// clang-format off

static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    Library_nf_lib_nf_lib_Display_LiquidCrystal_I2C::NativeTest___STATIC__BOOLEAN__BOOLEAN,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nf_lib =
{
    "nf_lib",
    0x559CC8DF,
    method_lookup,
    { 1, 0, 0, 0 }
};

// clang-format on
